spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  json:
    value:
      default:
        type: com.chg.hackdays.chappie.model.Message
    use:
      type:
        headers: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: ${DATASOURCE:jdbc:postgresql://10.0.1.1:5432/chappie}
    username: chappie
    password: chappie
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
kafka:
  bootstrapAddress: ${KAFKA_HOSTS:k1.local:9092,k2.local:9092,k3.local:9092}
  groupId: chappie
  defaultTopic: chat
chatbot:
  id: test
  rasa:
    url:
      base: ${RASA_HOST:http://localhost:5005}
      webhook: /webhooks/rest/webhook
timeentry:
  url:
    base: ${TIMEENTRY_HOST:http://localhost:8089}
    providerInfo: /getProviderInfo
chappie:
  server-id: ${CHAPPIE_SERVER_ID:server}
  db:
    url:
      base: ${DB_ADAPTER_HOST:http://localhost:8081}
      message: /message
      conversation: /conversation
      user: /user